map_path: ./media/map.png
scale:
  distance_cm: 93.0
  distance_pixels: 88.0056816347672
sensors:
  cortina_salon:
    humedad:
      last_update: '2024-08-16 01:12:34.293'
      state: 61.0
      topic: homeassistant/sensor/cortina_salon_humedad/state
    position_px: [1668, 290, 91]
    position_z_cm: 217
    temperatura:
      last_update: '2024-08-16 01:12:34.270'
      state: 25.3
      topic: homeassistant/sensor/cortina_salon_temperatura/state
  telefonillo:
    humedad:
      last_update: '2024-08-16 01:03:02.974'
      state: 55.0
      topic: homeassistant/sensor/telefonillo_humedad/state
    position_px: [1191, 307, 60]
    position_z_cm: 144
    temperatura:
      last_update: '2024-08-16 01:03:02.929'
      state: 28.2
      topic: homeassistant/sensor/telefonillo_temperatura/state
  th_bano_entrada:
    humedad:
      last_update: '2024-08-16 00:32:07.328'
      state: 61.0
      topic: homeassistant/sensor/th_bano_entrada_humedad/state
    position_px: [1060, 439, 44]
    position_z_cm: 107
    temperatura:
      last_update: '2024-08-16 00:32:07.319'
      state: 27.3
      topic: homeassistant/sensor/th_bano_entrada_temperatura/state
  th_bano_habitacion:
    humedad:
      last_update: '2024-08-16 01:01:50.034'
      state: 60.0
      topic: homeassistant/sensor/th_bano_habitacion_humedad/state
    position_px: [250, 377, 49]
    position_z_cm: 117
    temperatura:
      last_update: '2024-08-16 00:32:07.339'
      state: 27.3
      topic: homeassistant/sensor/th_bano_habitacion_temperatura/state
  th_cocina:
    humedad:
      last_update: '2024-08-16 01:12:28.439'
      state: 56.0
      topic: homeassistant/sensor/th_cocina_humedad/state
    position_px: [1377, 378, 47]
    position_z_cm: 114
    temperatura:
      last_update: '2024-08-16 01:12:28.423'
      state: 31.6
      topic: homeassistant/sensor/th_cocina_temperatura/state
  th_h_invitados:
    humedad:
      last_update: '2024-08-16 00:32:07.447'
      state: 58.0
      topic: homeassistant/sensor/th_h_invitados_humedad/state
    position_px: [800, 97, 32]
    position_z_cm: 77
    temperatura:
      last_update: '2024-08-16 00:32:07.436'
      state: 29.5
      topic: homeassistant/sensor/th_h_invitados_temperatura/state
  th_habitacion:
    humedad:
      last_update: '2024-08-16 00:32:07.468'
      state: 53.0
      topic: homeassistant/sensor/th_habitacion_humedad/state
    position_px: [66, 152, 18]
    position_z_cm: 44
    temperatura:
      last_update: '2024-08-16 00:49:58.944'
      state: 29.2
      topic: homeassistant/sensor/th_habitacion_temperatura/state
  th_impresora:
    humedad:
      last_update: '2024-08-16 00:32:07.490'
      state: 60.0
      topic: homeassistant/sensor/th_impresora_humedad/state
    position_px: [365, 296, 46]
    position_z_cm: 110
    temperatura:
      last_update: '2024-08-16 01:12:33.219'
      state: 30.4
      topic: homeassistant/sensor/th_impresora_temperatura/state
  th_pasillo:
    humedad:
      last_update: '2024-08-16 01:12:34.723'
      state: 55.0
      topic: homeassistant/sensor/th_pasillo_humedad/state
    position_px: [560, 457, 26]
    position_z_cm: 64
    temperatura:
      last_update: '2024-08-16 00:32:07.501'
      state: 29.1
      topic: homeassistant/sensor/th_pasillo_temperatura/state
  th_plantitas_salon:
    humedad:
      last_update: '2024-08-16 00:34:55.613'
      state: 55.0
      topic: homeassistant/sensor/th_plantitas_salon_humedad/state
    position_px: [1210, 182, 30]
    position_z_cm: 73
    temperatura:
      last_update: '2024-08-16 00:49:55.562'
      state: 28.5
      topic: homeassistant/sensor/th_plantitas_salon_temperatura/state
  th_terraza:
    humedad:
      last_update: '2024-08-16 01:11:33.115'
      state: 64.0
      topic: homeassistant/sensor/th_terraza_humedad/state
    position_px: [1594, 384, 52]
    position_z_cm: 125
    temperatura:
      last_update: '2024-08-16 01:11:33.104'
      state: 24.9
      topic: homeassistant/sensor/th_terraza_temperatura/state
  th_ventana_habitacion:
    humedad:
      last_update: '2024-08-16 00:39:38.271'
      state: 60.0
      topic: homeassistant/sensor/th_ventana_habitacion_humedad/state
    position_px: [362, 111, 62]
    position_z_cm: 149
    temperatura:
      last_update: '2024-08-16 00:39:38.265'
      state: 26.5
      topic: homeassistant/sensor/th_ventana_habitacion_temperatura/state
  th_ventana_salon:
    humedad:
      last_update: '2024-08-16 01:05:19.812'
      state: 69.0
      topic: homeassistant/sensor/th_ventana_salon_humedad/state
    position_px: [1682, 112, 40]
    position_z_cm: 96
    temperatura:
      last_update: '2024-08-16 01:05:19.805'
      state: 23.2
      topic: homeassistant/sensor/th_ventana_salon_temperatura/state
  tv_remote:
    humedad:
      last_update: '2024-08-16 01:12:36.138'
      state: 56.0
      topic: homeassistant/sensor/tv_remote_humedad/state
    position_px: [1426, 341, 17]
    position_z_cm: 42
    temperatura:
      last_update: '2024-08-16 01:03:04.914'
      state: 28.4
      topic: homeassistant/sensor/tv_remote_temperatura/state
temperature_in_height: 120
