map_path: ./media/map.png
scale:
  distance_cm: 93.0
  distance_pixels: 22
sensors:
  cortina_salon:
    position_px: [306, 57, 91]
    position_z_cm: 217
  telefonillo:
    position_px: [309, 531, 60]
    position_z_cm: 144
  th_bano_entrada:
    position_px: [440, 662, 44]
    position_z_cm: 107
  th_bano_habitacion:
    position_px: [379, 1473, 49]
    position_z_cm: 117
  th_cocina:
    position_px: [385, 343, 47]
    position_z_cm: 114
  th_h_invitados:
    position_px: [97, 894, 32]
    position_z_cm: 77
  th_habitacion:
    position_px: [152, 1648, 18]
    position_z_cm: 44
  th_impresora:
    position_px: [283, 1350, 46]
    position_z_cm: 110
  th_pasillo:
    position_px: [460, 1161, 26]
    position_z_cm: 64
  th_plantitas_mesa:
    position_px: [29, 27, 17]
    position_z_cm: 42
  th_plantitas_salon:
    position_px: [255, 501, 30]
    position_z_cm: 73
  th_terraza:
    position_px: [384, 128, 52]
    position_z_cm: 125
  th_ventana_habitacion:
    position_px: [104, 1344, 62]
    position_z_cm: 149
  th_ventana_salon:
    position_px: [116, 37, 40]
    position_z_cm: 96
  tv_remote:
    position_px: [329, 324, 17]
    position_z_cm: 42
temperature_in_height: 120
